baseURL = 'https://5h9igzqanx.github.io/TRDWBST-pages-blog'
languageCode = 'zh-cn'
title = 'TRDWBST-pages-blog'
theme = 'TRDWBST-pages-blog-theme'

[markup]
    [markup.tableOfContents]
        endLevel = 6
        ordered = false
        startLevel = 2
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
    [markup.highlight]
        style="witchhazel"
        noClasses = true
        lineNos = true
        lineNoStart = 1
        lineNumbersInTable = false
        guessSyntax = true