baseURL = 'https://5h9igzqanx.github.io/TRDWBST-pages-blog/'
languageCode = 'zh-cn'
title = 'TRDWBST-pages-blog'

[[menus.main]]
name = '主页'
pageRef = 'https://5h9igzqanx.github.io/TRDWBST/'
url = 'https://5h9igzqanx.github.io/TRDWBST/'
weight =10

[[menus.main]]
name = '仓库'
pageRef = 'https://github.com/5h9igzqanx/TRDWBST-pages-blog'
url = 'https://github.com/5h9igzqanx/TRDWBST-pages-blog'
weight = 20

[[menus.main]]
name = '投稿'
pageRef = '/'
url = '/'
weight = 30

[[menus.main]]
name = '标签'
pageRef = '/tags'
url   = '/tags'
weight = 40

[blackfriday]
toc=true
toc_depth=9

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
