baseURL = 'https://example.org/'
languageCode = 'zh-cn'
title = 'TRDWBST-pages-blog'

[[menus.main]]
name = '投稿'
pageRef = '/'
url = '/'
weight = 10

[[menus.main]]
name = '标签'
pageRef = '/tags'
url   = '/tags'
weight = 20

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
