baseURL = 'https://5h9igzqanx.github.io/TRDWBST-pages-blog/'
languageCode = 'zh-cn'
title = 'TRDWBST-pages-blog'

[[menus.main]]
name = '回到TRDWBST'
pageRef = 'https://5h9igzqanx.github.io/TRDWBST/'
url = 'https://5h9igzqanx.github.io/TRDWBST/'
weight =10

[[menus.main]]
name = 'Github仓库'
pageRef = 'https://github.com/5h9igzqanx/TRDWBST-pages-blog'
url = 'https://github.com/5h9igzqanx/TRDWBST-pages-blog'
weight = 20

[[menus.main]]
name = '归档'
pageRef = '/archives'
url = '/archives'
weight = 30

[[menus.main]]
name = '分类'
pageRef = '/categories'
url   = '/categories'
weight = 40

[[menus.main]]
name = '标签'
pageRef = '/tags'
url   = '/tags'
weight = 50

[[menus.main]]
name = '关于'
pageRef = '/about'
url = '/about'
weight = 60

[blackfriday]
toc=true
toc_depth=12

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
