name: Deploy to GitHub Pages

on:
  push:
    branches:
      - yuanDaiMa # 当源码仓库的主分支有变动时触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'

    - name: Build
      run: hugo --minify

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: ./public
        github_token: ${{ secrets.GITHUB_PAGES_TOKEN }}
