name: Deploy to GitHub Pages

on:
  push:
    branches:
      - yuanDaiMa # 假设源码变更发生在'yuanDaiMa'分支

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source Branch
      uses: actions/checkout@v2
      with:
        ref: 'yuanDaiMa' # 检出'yuanDaiMa'分支
        submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'

    - name: Build Hugo Site
      run: hugo --minify --baseURL "https://5h9igzqanx.github.io/TRDWBST-pages-blog"

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_branch: buShu # 部署到'buShu'分支
        publish_dir: ./public
        github_token: ${{ secrets.TRDWBST_PAGES_BLOG_AUTOUPD }}
